[tool.isort]
src_paths = [
    "pyagentspec/src",
    "pyagentspec/tests",
]
profile = "black"
line_length = 100

[tool.black]
line-length = 100

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = [
    'tests.*',
    'setup',
]
ignore_errors = true
