[tool.isort]
src_paths = [
    "pyagentspec/src",
    "pyagentspec/tests",
    "adapters/autogenagentspecadapter/src",
    "adapters/autogenagentspecadapter/tests",
    "adapters/langgraphagentspecadapter/src",
    "adapters/langgraphagentspecadapter/tests",
]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = [
    'tests.*',
    'setup',
]
ignore_errors = true

[[tool.mypy.overrides]]
module = [
    "fastapi",
    "fastapi.*",
    "uvicorn",
    "uvicorn.*",
]
ignore_errors = true
