# Copyright Â© 2025 Oracle and/or its affiliates.
#
# This software is under the Apache License 2.0
# (LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0) or Universal Permissive License
# (UPL) 1.0 (LICENSE-UPL or https://oss.oracle.com/licenses/upl), at your option.

$referenced_components:
  28yu3egh:
    component_type: ControlFlowEdge
    description: null
    from_node:
      $ref: nxbcwoiauhbjv
    id: 28yu3egh
    name: ctrl_edge_2
    to_node:
      $ref: 724893yhrj
  67uyh5423hje:
    component_type: DataFlowEdge
    description: null
    destination_input: Input_2
    destination_node:
      $ref: 724893yhrj
    id: 67uyh5423hje
    name: data_edge_2
    source_output: Output_2
    source_node:
      $ref: nxbcwoiauhbjv
  722njqbakhcsa:
    component_type: DataFlowEdge
    description: null
    destination_input: Input_3
    destination_node:
      $ref: 724893yhrj
    id: 722njqbakhcsa
    name: data_edge_3
    source_output: Output_1
    source_node:
      $ref: lniwuebjsdvkc
  724893yhrj:
    component_type: EndNode
    description: null
    id: 724893yhrj
    inputs:
      - additionalProperties:
          type: string
        default: { }
        properties: { }
        title: Input_2
        type: object
      - default: null
        title: Input_3
        type:
          - 'null'
          - string
    name: Node 3
    outputs:
      - default: true
        title: Output_2
        type: boolean
      - default: 1
        title: Output_3
        type: number
  99asbdiugjk4b5:
    component_type: VLLMConfig
    default_generation_parameters: {}
    description: llama 3.1 config
    id: 99asbdiugjk4b5
    model_id: llama3.1-8b-instruct
    name: LLama 3.1 8b
    url: url.to.my.llm.com/hostedllm:12345
  buhdgsbjmn:
    component_type: DataFlowEdge
    description: null
    destination_input: Input_2
    destination_node:
      $ref: nxbcwoiauhbjv
    id: buhdgsbjmn
    name: data_edge_1
    source_output: Output_1
    source_node:
      $ref: lniwuebjsdvkc
  lniwuebjsdvkc:
    component_type: StartNode
    description: null
    id: lniwuebjsdvkc
    inputs:
      - default: input_1_default
        title: Input_1
        type: string
    name: Node 1
    outputs:
      - items:
          items:
            type: string
          type: array
        title: Output_1
        type: array
  nh32tewsaicjkl:
    component_type: ControlFlowEdge
    description: null
    from_node:
      $ref: lniwuebjsdvkc
    id: nh32tewsaicjkl
    name: ctrl_edge_1
    to_node:
      $ref: nxbcwoiauhbjv
  nxbcwoiauhbjv:
    component_type: LLMNode
    description: null
    id: nxbcwoiauhbjv
    inputs:
      - additionalProperties:
          type: string
        default: { }
        properties: { }
        title: Input_2
        type: object
      - default: null
        title: Input_3
        type:
          - 'null'
          - string
    llmconfig:
      $ref: 99asbdiugjk4b5
    name: Node 2
    outputs:
      - default: true
        title: Output_2
        type: boolean
    prompt_template: This is the prompt! {{ Input_2 }} {{ Input_3 }}
  component_type: Flow
  description: null
  id: mmnhagawse
  data_flow_connections:
    - $ref: buhdgsbjmn
    - $ref: 67uyh5423hje
    - $ref: 722njqbakhcsa
  inputs:
    - default: input_1_default
      title: Input_1
      type: string
    - additionalProperties:
        type: string
      default: { }
      properties: { }
      title: Input_2
      type: object
  name: Example test flow
  outputs:
    - default: true
      title: Output_2
      type: boolean
    - default: 1
      title: Output_3
      type: number
  start_node:
    $ref: lniwuebjsdvkc
  nodes:
    - $ref: lniwuebjsdvkc
    - $ref: nxbcwoiauhbjv
    - $ref: 724893yhrj
  control_flow_connections:
    - $ref: nh32tewsaicjkl
    - $ref: 28yu3egh
agentspec_version: 25.4.1
